# Generated by Django 5.0.2 on 2024-03-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='size',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
