# Generated by Django 5.0.2 on 2024-03-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_files_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='size',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
