# Generated by Django 5.0.2 on 2024-03-14 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_alter_files_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='linkUiid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
