# Generated by Django 5.0.2 on 2024-03-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_files_linkuiid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
