# Generated by Django 5.0.2 on 2024-03-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_alter_files_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='download_counter',
            field=models.IntegerField(default=0),
        ),
    ]
