# Generated by Django 5.0.2 on 2024-03-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_files_download_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesLinks',
        ),
    ]
