# Generated by Django 5.0.2 on 2024-03-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_rename_user_costumuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumUser',
        ),
    ]
